# Generated by Django 4.1.2 on 2023-04-30 11:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ocj', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solution',
            new_name='Submissions',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
