# Generated by Django 4.1.2 on 2023-05-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocj', '0002_rename_solution_submissions_delete_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissions',
            old_name='created_at',
            new_name='submission_time',
        ),
        migrations.RenameField(
            model_name='submissions',
            old_name='code',
            new_name='user_code',
        ),
        migrations.RemoveField(
            model_name='submissions',
            name='score',
        ),
        migrations.RemoveField(
            model_name='submissions',
            name='status',
        ),
        migrations.AddField(
            model_name='submissions',
            name='run_time',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='submissions',
            name='user_stderr',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='submissions',
            name='user_stdout',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='submissions',
            name='verdict',
            field=models.CharField(default='Wrong Answer', max_length=20),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='language',
            field=models.CharField(choices=[('C++', 'C++'), ('C', 'C'), ('Python3', 'Python3'), ('Java', 'Java')], default='C++', max_length=10),
        ),
    ]
